# Debe estar en el mismo directorio de gulpfile.js para no tener que parsear este .yml
rules:
  empty-line-between-blocks: 0
  hex-notation: 0
  indentation: 
    - 1
    - size: 4
  leading-zero: 0
  class-name-format:
    - 1
    -
      allow-leading-underscore: true
      convention: ^[a-z][a-zA-Z0-9]*(__)?([a-z][a-zA-Z0-9]*)?(--)?([a-z][a-zA-Z0-9]*)?$
  mixin-name-format: 
    - 1
    -
      allow-leading-underscore: false
      convention: 'camelcase'
  no-color-literals: 0
  no-important: 2
  no-qualifying-elements: 0
  shorthand-values: 0
  variable-name-format:
    - 1
    - 
      allow-leading-underscore: false
      convention: 'camelcase'
