<style type="text/css">
    .media-upload ul {
        margin: 10px 0 0;
    }
    .media-upload li,
    .media-upload li.vacio {
        display: inline-block;
        position: relative;
        margin: 0 6px 6px 0;
        line-height: 1;
    }
    .media-upload li.vacio {
        background: #aaa;
        width: 150px;
        height: 150px;
    }
    .media-upload li img {
        width: 150px;
        height: 150px;
        display: block;
    }
    .media-upload li .eliminar,
    .media-upload li .reemplazar {
        position: absolute;
        right: 5px;
        top: 5px;
    }
    .media-upload li .reemplazar {
        top: auto;
        bottom: 5px;
    }
</style>
<?php wp_nonce_field('metabox_galeria', 'metabox_galeria_nonce'); ?>
<div class="media-upload">
    <button type="button" class="button cargarImagenJS">Agregar imagenes</button>
    <?php $formato = '<li><input type="hidden" value="%s" class="media-url" name="galeria[]" /> <img src="%s" /> <button type="button" class="button eliminar">Eliminar</button> <button type="button" class="button reemplazar">Reemplazar</button> </li>'; ?>
    <ul>
        <?php
        foreach($galeria as $id => $src) {
            printf($formato, $id, $src[0]);
        } ?>
    </ul>
    <p><span><?php echo $maximo - count($galeria); ?></span> imagenes disponibles de <?php echo $maximo; ?></p>
</div>
<script type="text/javascript">
    var input = '<?php printf($formato, '', '') ?>';
    var maximo = <?php echo $maximo; ?>;
</script>
