<?php 
/** Este template se usa como widget y como metabox. */

if (!isset($galeria) || !is_array($galeria)) $galeria = array();
if (!isset($cantidadMaxima)) $cantidadMaxima = -1;
$name = (isset($this) && is_object($this)) ? $this->get_field_name('galeria') : 'galeria';
?>
<div class="componente-galeria" data-maximo="<?php echo $cantidadMaxima ?>" data-name-input="<?php echo $name; ?>[]">
    <?php if ($cantidadMaxima >= 0): ?>
        <p>Imagenes usadas: <span class="cantidadActual"><?php echo count($galeria); ?></span> de <?php echo $cantidadMaxima; ?></p>
    <?php else: ?>
        <p>Imágenes:</p>
    <?php endif ?>
    <ul>
    <?php foreach($galeria as $id): ?>
        <?php $src = wp_get_attachment_image_src($id); ?>
        <li class="thumb">
            <input type="hidden" value="<?php echo $id ?>" name="<?php echo $name; ?>[]" />
            <img src="<?php echo $src[0] ?>" />
            <button type="button" class="eliminar" title="Eliminar esta imagen">X</button> <button type="button" class="reemplazar" title="Reemplazar esta imagen">Reemplazar imagen</button>
        </li>
    <?php endforeach; ?>
    </ul>
    <button type="button" class="button button-primary cargarImagen cargarImagenJS">Agregar imagenes</button>
</div>
